# -*- coding: utf-8 -*-
# Copyright 2020-Today TechKhedut.
# Part of TechKhedut. See LICENSE file for full copyright and licensing details.
{
    'name': "Veterinary Management",
    'summary': """Veterinary Management""",
    'description': """Veterinary Management""",
    'category': 'Tools',
    'version': '2.2.0',
    'author': 'TechKhedut Inc.',
    'company': 'TechKhedut Inc.',
    'maintainer': 'TechKhedut Inc.',
    'website': "https://www.techkhedut.com",
    'depends': ['contacts', 'mail', 'product', 'sale_management', 'stock', 'account'],
    'data': [
        # Security
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        # Data
        'data/sequence.xml',
        'data/data.xml',
        'data/hospital_product_data.xml',
        'data/ir_cron.xml',
        # Wizards
        'wizard/appointment_wizard_view.xml',
        'wizard/appointment_details_wizard_view.xml',
        # Views
        'views/assets.xml',
        'views/patient_views.xml',
        'views/disease_views.xml',
        'views/disease_details_views.xml',
        'views/staff_views.xml',
        'views/patient_case_view.xml',
        'views/vaccination_views.xml',
        'views/appointment_views.xml',
        'views/medicine_views.xml',
        'views/hospital_prescription_view.xml',
        'views/medical_report_view.xml',
        'views/animal_type_views.xml',
        'views/vaccine_views.xml',
        'views/patient_report_view.xml',
        'views/report_document_view.xml',
        'views/surgery_tag_view.xml',
        'views/surgery_details_view.xml',
        'views/patient_surgery_details.xml',
        'views/contact_patient_inherit.xml',
        'views/hospital_maintenance_view.xml',
        'views/hospital_room_view.xml',
        'views/admit_patient_details_views.xml',
        'views/grooming_type_view.xml',
        'views/grooming_details_view.xml',
        'views/training_type_view.xml',
        'views/training_details_view.xml',
        'views/grooming_product_view.xml',
        'views/maintenance_service_views.xml',
        'views/model_views.xml',
        # Menus
        'views/menus.xml',
        # Reports
        'report/prescription_report_template.xml',
        'report/patient_case_report_template.xml',
        'report/training_certificate_template.xml',
    ],
    'qweb': [
        "static/src/xml/template.xml",
    ],
    'images': ['static/description/cover.gif'],
    'price': 150,
    'currency': 'EUR',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
}
